spring:
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: aar-local-db
    password: test1234
    url: jdbc:mysql://localhost:3306

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: kakao-client-id
            client-secret: kakao-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/aar/authn/login/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
aar:
  authn:
    frontend-redirect-uri: http://localhost:8080

logging:
  level:
    root: debug
